export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_DAY = 'SET_DAY'
export const SET_API_CALLING_STATUS = 'SET_API_CALLING_STATUS'

export const GET_DAILY_MEAL = 'GET_DAILY_MEAL'
export const GET_WEEKLY_MEAL = 'GET_WEEKLY_MEAL'
export const GET_SELECTED_PERIOD_MEAL = 'GET_SELECTED_PERIOD_MEAL'
